# Generated by Django 4.0 on 2021-12-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('jan_code', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='media/%m/')),
            ],
        ),
    ]
