# Generated by Django 4.0 on 2021-12-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='jan_code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
